### ISSUE TITLE
Allow Conversion from Binary files to HDF5

### ISSUE THREAD

**Issue by joshcalcino** [joshcalcino/PySplashSPH#3]
PySPLASH should be able to read in binary formats and then save them as HDF5 files.

As an additional plus, this will hopefully allow the binary data to be accessible as an HDF5 object.

**Comment by danieljprice** [comment]
but what do you propose for the output hdf5 format? There is no standard for this. There are many possible standards that rely on hdf5 (e.g. silo, h5part)

**Comment by joshcalcino** [comment]
Whatever the most natural form is in Python. HDF5 objects are basically just Python dictionaries, but with additional attributes. Saving/reading from Python won't be an issue, but saving a binary file to HDF5, and then trying to read this HDF5 file with splash, might be an issue. 

I need to look into it more.

**Comment by dmentipl** [comment]
Accessing the data in the Phantom-HDF5 format is quite simple (with h5py). Particle arrays are accessed like `file["particles/xyz"]`, for example. Sink arrays are accessed like `file["sinks/spinxyz"]`, for example. And header quantities are accessed like `file["header/alpha"]`, for example.

Using h5py you can see what arrays are available like

```python
>>> list(file["particles"])
['divv', 'dt', 'dustfrac', 'h', 'itype', 'tstop', 'vxyz', 'xyz']
```

Or header quantities like

```python
>>> list(f["header"])
['Bextx',
 'Bexty',
 'Bextz',
 'C_cour',
 'C_force',
 'RK2',
 'alpha',
 ...,
 'zmin']
```

@joshcalcino : I guess what you're saying here

> PySPLASH should be able to read in binary formats and then save them as HDF5 files.

is that PySPLASH could do the phantom2hdf5 conversion? You might have to be careful with this as phantom2hdf5 needs to be compiled with the same Makefile flags as the original data or else data might be lost in conversion.

**Comment by dmentipl** [comment]
Both silo and h5part seem to be unmaintained. h5part has been superseded by h5hut. But either way it doesn't seem necessary to use a wrapper around HDF5. The Phantom source code contains utilities for reading and writing HDF5 datasets with Fortran.

**Comment by joshcalcino** [comment]
Thanks for that summary Daniel. I'll attempt to wrap quantities in the way how you have done with the Phantom-HDF5 format, so hopefully Pysplash can be called to read binary files, and return an HDF5 Dataset class object with the particle, sink, and header arrays accessed in the same way as you describe above.

**Comment by joshcalcino** [comment]
>  You might have to be careful with this as phantom2hdf5 needs to be compiled with the same Makefile flags as the original data or else data might be lost in conversion.

Given that pysplash is getting the data directly from splash, I don't think that should be an issue (I could be wrong). I think that splash not being able to read data from different phantom version would be a critical issue, and probably something that Daniel Price has had to deal with already.

**Comment by danieljprice** [comment]
I would like to clarify a more general issue here, namely reading from other data formats (non-phantom). Obviously other codes do not spit out the same quantities as phantom, nor do they spit out the same header quantities. So I would like to ensure that nothing is hardwired to "know" what the data labels mean (this applies especially for the header quantities, they can be completely arbitrary and for some do not even contain the time). In splash this is handled by simply reading the header tags (headertags) and their values (headervals), splash does not know anything about what these mean, except for the time. One cannot assume that any other header values are present, in general.

**Comment by joshcalcino** [comment]
Alright, fair enough, I can make a generic hdf5 file object that will work for any format, but then make a specific exception for phantom.

**Comment by joshcalcino** [comment]
This is now somewhat supported with v0.0.2.
