### ISSUE TITLE
PySsplashSPH ERROR: Could not load `libexact.so`

### ISSUE THREAD

**Issue by bjnorfolk** [joshcalcino/PySplashSPH#4]
Hi,

Getting the error: ```PySsplashSPH ERROR: Could not load `libexact.so``` when attempting to load a dump file.

Originally thought it was due to splash not being installed my system, but after install the error still persisted. I believe I've exported the directory correctly given I can call splash from the bash. Here's the exports I have for splash:
```
export SPLASH_DIR=$HOME/splash
export PATH=$PATH:$SPLASH_DIR/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SPLASH_DIR/giza/lib
```

Any tips?

**Comment by joshcalcino** [comment]
Can I confirm you are using the most recent version of Splash (v3.0.1)? 

If so, cd to your splash directory and try

```make lib```

That should compile the libexact and libread libraries, which can then be discoverable by pysplash.

**Comment by joshcalcino** [comment]
Also could you try 

```cd /pysplashsph/pysplashsph/libs```

Let me know if the libs are in those directories. If not, there might have been a compiler issue.

**Comment by bjnorfolk** [comment]
Sorry for the delay, I'm installing on wsl (Windows Subsystem for Linux) and the paths are not straight forward.

So I'm on Splash v3.01 - I did have to install from git though, the "stable" install (```sudo apt-get install splash```) is v2...

The  ``` make lib ``` didn't fix the issue.

Here's my libs path ```/home/bnorfolk/anaconda3/envs/py3/lib/python3.8/site-packages/pysplashsph/libs``` it has both ```libexact.so ``` and ```libread.so ```

**Comment by joshcalcino** [comment]
I am also on WSL. Alright I understand what is happening now.

So basically PySplash is getting caught up with your install of Splash (because it defaults to searching for this directory) rather than using the compiled version it makes.

I'll change this so that only occurs when specified.

In the meantime, you can fix this issue by not setting SPLASH_DIR, or just compiling splash straight from the github page, rather than using apt-get. I don't think the version on apt-get is updated often.

I've found that installing splash via github reliably works once you install the necessary libraries on WSL (e.g. hdf5, cfitsio)

But as a first step can you try

```unset SPLASH_DIR```

then try running your code?

**Comment by joshcalcino** [comment]
Sorry I should read your comment more thoroughly first..

> So I'm on Splash v3.01 - I did have to install from git though, the "stable" install

It looks like libexact is not getting compiled. I'll try this out. Not sure why I am not getting this issue myself, since the setup is nearly the same.

**Comment by bjnorfolk** [comment]
Just a heads up, I did the install on my macbook pro and the same error occurred - so it's safe to assume it's not something I've stuffed up with wsl paths.

**Comment by dliptai** [comment]
@bjnorfolk the new version `v0.0.2.post.1` should fix this problem. Can you try reinstalling pysplashsph to confirm that it works? There was an issue with the previous build uploaded to PyPI, which meant that the included `libexact.so` library was not suitable for your system.

> So basically PySplash is getting caught up with your install of Splash (because it defaults to searching for this directory) rather than using the compiled version it makes.

@joshcalcino pysplashspsh will only compile splash when installing from source. Hence there's no need to have a local copy of splash installed for any user, unless they are trying to install pysplashsph manually from source (i.e. not via a pip install).

The code will always look for libraries under the subdirectory `libs/`
e.g. `~/anaconda/lib/python3.7/site-packages/pysplashsph/libs/libexact.so`

**Comment by bjnorfolk** [comment]
Yep the reinstall fixed it @dliptai 
Now getting the issue:
``` python
Traceback (most recent call last):
  File "fortran_2_hdf5.py", line 11, in <module>
    snap = plonk.load_snap(data_binary_as_hdf5)
  File "/Users/brodienorfolk/anaconda3/envs/pysplash_test/lib/python3.8/site-packages/plonk/snap/__init__.py", line 20, in load_snap
    return Snap().load_snap(filename=filename, data_source=data_source, config=config)
  File "/Users/brodienorfolk/anaconda3/envs/pysplash_test/lib/python3.8/site-packages/plonk/snap/snap.py", line 161, in load_snap
    file_path = Path(filename).expanduser()
  File "/Users/brodienorfolk/anaconda3/envs/pysplash_test/lib/python3.8/pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "/Users/brodienorfolk/anaconda3/envs/pysplash_test/lib/python3.8/pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/brodienorfolk/anaconda3/envs/pysplash_test/lib/python3.8/pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not File
```
Not sure if this is a plonk issue or the way pysplashsph has created the hdf5 file?

**Comment by dliptai** [comment]
I don’t think plonk takes abstract data types as input yet. @joshcalcino may know more, but as I understand it the solution at the moment is to load the file via pysplashsph, save to an hdf5 file,  then load the hdf5 file with plonk.

**Comment by dliptai** [comment]
i.e. plonk.load_snap() requires a path to a file as input

**Comment by bjnorfolk** [comment]
Ok, simple question then - how do you save the hdf5 file?

**Comment by joshcalcino** [comment]
The newest version of Plonk will take an HDF5 File object as an input, you will need to update plonk to access this functionality. 

You save the hdf5 file using `dump.save_hdf5()`. Note that save_hdf5 is an attribute of the dump class, not an attribute of the File object that is returned by `dump.as_hdf5()`.

**Comment by dmentipl** [comment]
Just to clarify, Plonk does not currently (v0.7.3) take an HDF5 File object as input. It currently requires an actual HDF5 file.

**Comment by joshcalcino** [comment]
Oh sorry about that. I thought that was implemented now.
